import type { SkillRegistry } from './types';

export const SKILL_REGISTRY: SkillRegistry = {
  // NSE Technical Analysis (9 skills)
  'nse-trading-toolkit': {
    name: 'nse-trading-toolkit',
    displayName: 'NSE Trading Toolkit',
    description: 'Foundation kit for technical analysis: charts, indicators, signals',
    category: 'nse-technical',
    icon: '🛠️',
    params: [],
    visualizationType: 'chart',
    estimatedExecutionTimeMs: 2000,
  },
  'rsi-divergence': {
    name: 'rsi-divergence',
    displayName: 'RSI Divergence',
    description: 'Hidden divergence detection for bullish/bearish signals',
    category: 'nse-technical',
    icon: '📊',
    params: [],
    visualizationType: 'table',
    estimatedExecutionTimeMs: 1500,
  },
  'multi-timeframe-analysis': {
    name: 'multi-timeframe-analysis',
    displayName: 'Multi-Timeframe Analysis',
    description: 'Cross-timeframe confirmation (daily, weekly, monthly)',
    category: 'nse-technical',
    icon: '⏱️',
    params: [],
    visualizationType: 'text',
    estimatedExecutionTimeMs: 2500,
  },
  'fibonacci-trading': {
    name: 'fibonacci-trading',
    displayName: 'Fibonacci Levels',
    description: 'Support/resistance levels using Fibonacci retracements',
    category: 'nse-technical',
    icon: '📐',
    params: [],
    visualizationType: 'chart',
    estimatedExecutionTimeMs: 1800,
  },
  'position-sizing': {
    name: 'position-sizing',
    displayName: 'Position Sizing',
    description: 'Kelly Criterion & ATR-based position sizing',
    category: 'nse-technical',
    icon: '💰',
    params: [],
    visualizationType: 'table',
    estimatedExecutionTimeMs: 1200,
  },
  'stop-loss-strategies': {
    name: 'stop-loss-strategies',
    displayName: 'Stop-Loss Strategies',
    description: 'Trailing stops and volatility-adjusted exit levels',
    category: 'nse-technical',
    icon: '🛑',
    params: [],
    visualizationType: 'text',
    estimatedExecutionTimeMs: 1500,
  },
  'trailing-stops': {
    name: 'trailing-stops',
    displayName: 'Trailing Stops',
    description: 'Dynamic exit management with trailing stop losses',
    category: 'nse-technical',
    icon: '📉',
    params: [],
    visualizationType: 'gauge',
    estimatedExecutionTimeMs: 1300,
  },
  'risk-reward-ratio': {
    name: 'risk-reward-ratio',
    displayName: 'Risk-Reward Ratio',
    description: 'Validate risk/reward before entry, target minimum 1:2',
    category: 'nse-technical',
    icon: '⚖️',
    params: [],
    visualizationType: 'gauge',
    estimatedExecutionTimeMs: 800,
  },
  'nse-technical-analysis': {
    name: 'nse-technical-analysis',
    displayName: 'NSE Technical Suite',
    description: 'Comprehensive technical analysis (MACD, SMA, RSI, volume)',
    category: 'nse-technical',
    icon: '📈',
    params: [],
    visualizationType: 'chart',
    estimatedExecutionTimeMs: 3000,
  },

  // InvestSkill Suite (16 skills)
  'invest-dcf-valuation': {
    name: 'invest-dcf-valuation',
    displayName: 'DCF Valuation',
    description: 'Discounted cash flow analysis & intrinsic value',
    category: 'invest-fundamental',
    icon: '💹',
    params: [],
    visualizationType: 'gauge',
    estimatedExecutionTimeMs: 2500,
  },
  'invest-piotroski-f-score': {
    name: 'invest-piotroski-f-score',
    displayName: 'Piotroski F-Score',
    description: 'Financial quality scoring (0-9 scale)',
    category: 'invest-fundamental',
    icon: '⭐',
    params: [],
    visualizationType: 'gauge',
    estimatedExecutionTimeMs: 1800,
  },
  'invest-earnings-call-analysis': {
    name: 'invest-earnings-call-analysis',
    displayName: 'Earnings Call Analysis',
    description: 'Management tone, guidance, and sentiment extraction',
    category: 'invest-research',
    icon: '🎙️',
    params: [],
    visualizationType: 'text',
    estimatedExecutionTimeMs: 2000,
  },
  'invest-insider-trading': {
    name: 'invest-insider-trading',
    displayName: 'Insider Trading',
    description: 'Insider buying/selling signals and conviction levels',
    category: 'invest-research',
    icon: '🤝',
    params: [],
    visualizationType: 'table',
    estimatedExecutionTimeMs: 1500,
  },
  'invest-sector-analysis': {
    name: 'invest-sector-analysis',
    displayName: 'Sector Rotation',
    description: 'Relative sector strength and rotation signals',
    category: 'invest-technical',
    icon: '🔄',
    params: [],
    visualizationType: 'chart',
    estimatedExecutionTimeMs: 2200,
  },
  'invest-dividend-analysis': {
    name: 'invest-dividend-analysis',
    displayName: 'Dividend Analysis',
    description: 'Yield, coverage, growth trends, and safety',
    category: 'invest-fundamental',
    icon: '💵',
    params: [],
    visualizationType: 'table',
    estimatedExecutionTimeMs: 1600,
  },
  'invest-fcf-analysis': {
    name: 'invest-fcf-analysis',
    displayName: 'Free Cash Flow',
    description: 'Operating cash flow, capex, and FCF trends',
    category: 'invest-fundamental',
    icon: '💧',
    params: [],
    visualizationType: 'chart',
    estimatedExecutionTimeMs: 1700,
  },
  'invest-eps-growth': {
    name: 'invest-eps-growth',
    displayName: 'EPS Growth Analysis',
    description: 'Earnings per share trajectory and growth rates',
    category: 'invest-fundamental',
    icon: '📊',
    params: [],
    visualizationType: 'chart',
    estimatedExecutionTimeMs: 1400,
  },
  'invest-price-targets': {
    name: 'invest-price-targets',
    displayName: 'Price Target Analysis',
    description: 'Consensus vs. current price and analyst targets',
    category: 'invest-research',
    icon: '🎯',
    params: [],
    visualizationType: 'gauge',
    estimatedExecutionTimeMs: 1200,
  },
  'invest-short-interest': {
    name: 'invest-short-interest',
    displayName: 'Short Interest',
    description: 'Bearish sentiment and short squeeze potential',
    category: 'invest-research',
    icon: '⬇️',
    params: [],
    visualizationType: 'text',
    estimatedExecutionTimeMs: 1000,
  },
  'invest-institutional-ownership': {
    name: 'invest-institutional-ownership',
    displayName: 'Institutional Ownership',
    description: 'Fund concentration and institutional investor tracking',
    category: 'invest-research',
    icon: '🏛️',
    params: [],
    visualizationType: 'table',
    estimatedExecutionTimeMs: 1500,
  },
  'invest-value-metrics': {
    name: 'invest-value-metrics',
    displayName: 'Value Metrics',
    description: 'PE, PB, PEG, EV/EBITDA, and valuation ratios',
    category: 'invest-fundamental',
    icon: '📐',
    params: [],
    visualizationType: 'table',
    estimatedExecutionTimeMs: 1300,
  },
  'invest-debt-analysis': {
    name: 'invest-debt-analysis',
    displayName: 'Debt Analysis',
    description: 'Leverage ratios, refinance risk, debt maturity',
    category: 'invest-fundamental',
    icon: '💳',
    params: [],
    visualizationType: 'gauge',
    estimatedExecutionTimeMs: 1400,
  },
  'invest-margin-analysis': {
    name: 'invest-margin-analysis',
    displayName: 'Margin Analysis',
    description: 'Operating and net margin trends and efficiency',
    category: 'invest-fundamental',
    icon: '📊',
    params: [],
    visualizationType: 'chart',
    estimatedExecutionTimeMs: 1200,
  },
  'invest-working-capital': {
    name: 'invest-working-capital',
    displayName: 'Working Capital',
    description: 'Cash conversion efficiency and working capital trends',
    category: 'invest-fundamental',
    icon: '⚙️',
    params: [],
    visualizationType: 'chart',
    estimatedExecutionTimeMs: 1300,
  },
  'invest-full-report': {
    name: 'invest-full-report',
    displayName: 'Full Research Report',
    description: 'Comprehensive institutional-grade research synthesis',
    category: 'invest-research',
    icon: '📄',
    params: [],
    visualizationType: 'text',
    estimatedExecutionTimeMs: 5000,
  },
};

export function getSkillsByCategory(category: string) {
  return Object.entries(SKILL_REGISTRY)
    .filter(([_, skill]) => skill.category === category)
    .map(([_, skill]) => skill);
}

export function getSkillManifest(skillName: string) {
  return SKILL_REGISTRY[skillName];
}

export function getAllSkills() {
  return Object.values(SKILL_REGISTRY);
}
