
export const mockStocks = [
    {
        id: "1",
        symbol: "TATASTEEL",
        name: "Tata Steel Ltd.",
        sector: "Metals & Mining",
        price: 154.5,
        market_cap: 189000,
        megatrend: ["Infra", "China+1"],
        quality_score: 85,
        status: "Active"
    },
    {
        id: "2",
        symbol: "HDFCBANK",
        name: "HDFC Bank Ltd.",
        sector: "Financials",
        price: 1450.0,
        market_cap: 1100000,
        megatrend: ["Financialization", "Consumption"],
        quality_score: 92,
        status: "Active"
    },
    {
        id: "3",
        symbol: "KPITTECH",
        name: "KPIT Technologies",
        sector: "Technology",
        price: 1500.25,
        market_cap: 41000,
        megatrend: ["Digital India", "EV"],
        quality_score: 78,
        status: "Watchlist"
    },
    { id: "4", symbol: "RELIANCE", name: "Reliance Industries", sector: "Oil & Gas", price: 2450.0, market_cap: 1600000, megatrend: ["Energy Transition"], quality_score: 95, status: "Active" },
    { id: "5", symbol: "INFY", name: "Infosys Ltd.", sector: "Technology", price: 1420.0, market_cap: 600000, megatrend: ["Digital India"], quality_score: 88, status: "Active" },
    { id: "6", symbol: "ITC", name: "ITC Ltd.", sector: "FMCG", price: 430.0, market_cap: 550000, megatrend: ["Consumption"], quality_score: 82, status: "Active" },
    { id: "7", symbol: "LT", name: "Larsen & Toubro", sector: "Infrastructure", price: 2900.0, market_cap: 400000, megatrend: ["Infra"], quality_score: 90, status: "Active" },
    { id: "8", symbol: "BAJFINANCE", name: "Bajaj Finance", sector: "Financials", price: 7200.0, market_cap: 450000, megatrend: ["Financialization"], quality_score: 89, status: "Active" },
    { id: "9", symbol: "ASIANPAINT", name: "Asian Paints", sector: "Materials", price: 3100.0, market_cap: 300000, megatrend: ["Consumption"], quality_score: 85, status: "Watchlist" },
    { id: "10", symbol: "TITAN", name: "Titan Company", sector: "Consumer Discretionary", price: 3400.0, market_cap: 300000, megatrend: ["Consumption"], quality_score: 87, status: "Active" },
    { id: "11", symbol: "MARUTI", name: "Maruti Suzuki", sector: "Automobile", price: 10500.0, market_cap: 320000, megatrend: ["Consumption"], quality_score: 84, status: "Active" },
    { id: "12", symbol: "ULTRACEMCO", name: "UltraTech Cement", sector: "Materials", price: 9800.0, market_cap: 280000, megatrend: ["Infra"], quality_score: 86, status: "Active" },
    { id: "13", symbol: "SUNPHARMA", name: "Sun Pharma", sector: "Healthcare", price: 1300.0, market_cap: 310000, megatrend: ["Healthcare"], quality_score: 83, status: "Active" },
    { id: "14", symbol: "NESTLEIND", name: "Nestle India", sector: "FMCG", price: 25000.0, market_cap: 240000, megatrend: ["Consumption"], quality_score: 91, status: "Active" },
    { id: "15", symbol: "JSWSTEEL", name: "JSW Steel", sector: "Metals & Mining", price: 850.0, market_cap: 200000, megatrend: ["Infra"], quality_score: 80, status: "Watchlist" },
    { id: "16", symbol: "TATAMOTORS", name: "Tata Motors", sector: "Automobile", price: 950.0, market_cap: 315000, megatrend: ["EV", "Consumption"], quality_score: 81, status: "Active" },
    { id: "17", symbol: "ADANIENT", name: "Adani Enterprises", sector: "Capital Goods", price: 3200.0, market_cap: 360000, megatrend: ["Infra", "Energy Transition"], quality_score: 75, status: "Watchlist" },
    { id: "18", symbol: "POWERGRID", name: "Power Grid Corp", sector: "Utilities", price: 280.0, market_cap: 260000, megatrend: ["Infra"], quality_score: 84, status: "Active" },
    { id: "19", symbol: "NTPC", name: "NTPC Ltd", sector: "Utilities", price: 340.0, market_cap: 330000, megatrend: ["Infra", "Energy Transition"], quality_score: 83, status: "Active" },
    { id: "20", symbol: "M&M", name: "Mahindra & Mahindra", sector: "Automobile", price: 1800.0, market_cap: 220000, megatrend: ["Consumption", "Rural Growth"], quality_score: 85, status: "Active" },
    { id: "21", symbol: "HCLTECH", name: "HCL Technologies", sector: "Technology", price: 1600.0, market_cap: 430000, megatrend: ["Digital India"], quality_score: 86, status: "Active" },
    { id: "22", symbol: "WIPRO", name: "Wipro Ltd", sector: "Technology", price: 520.0, market_cap: 270000, megatrend: ["Digital India"], quality_score: 79, status: "Watchlist" },
    { id: "23", symbol: "BHARTIARTL", name: "Bharti Airtel", sector: "Telecom", price: 1200.0, market_cap: 670000, megatrend: ["Digital India"], quality_score: 88, status: "Active" },
    { id: "24", symbol: "SBIN", name: "State Bank of India", sector: "Financials", price: 780.0, market_cap: 690000, megatrend: ["Financialization"], quality_score: 89, status: "Active" },
    { id: "25", symbol: "LTIM", name: "LTIMindtree", sector: "Technology", price: 6200.0, market_cap: 180000, megatrend: ["Digital India"], quality_score: 84, status: "Active" },
    { id: "26", symbol: "DIVISLAB", name: "Divi's Lab", sector: "Healthcare", price: 3800.0, market_cap: 100000, megatrend: ["Healthcare"], quality_score: 82, status: "Watchlist" },
    { id: "27", symbol: "PIDILITIND", name: "Pidilite Industries", sector: "Chemicals", price: 2900.0, market_cap: 147000, megatrend: ["Consumption"], quality_score: 93, status: "Active" },
    { id: "28", symbol: "BAJAJ-AUTO", name: "Bajaj Auto", sector: "Automobile", price: 8500.0, market_cap: 240000, megatrend: ["Consumption", "EV"], quality_score: 87, status: "Active" },
    { id: "29", symbol: "HAL", name: "Hindustan Aeronautics", sector: "Defense", price: 3500.0, market_cap: 230000, megatrend: ["Defense"], quality_score: 85, status: "Active" },
    { id: "30", symbol: "BEL", name: "Bharat Electronics", sector: "Defense", price: 210.0, market_cap: 153000, megatrend: ["Defense"], quality_score: 84, status: "Active" }
];
